### ISSUE TITLE
Este sitio rompio tu bot

### ISSUE THREAD

**Issue by horellana** [andreskrey/empleadoEstatalBot#3]
![foto](https://i.imgur.com/9GgiH4I.png)

[Post en reddit](https://www.reddit.com/r/chile/comments/6p2xa4/pelea_de_vendedores_ambulantes_en_estaci%C3%B3n_central/)
[Link al sitio](http://www.chvnoticias.cl/nacional/registraron-pelea-entre-comerciantes-ambulantes-en-estacion-central/2017-07-21/212843.html)

**Comment by andreskrey** [comment]
Tecnicamente es un "Not a bug": https://github.com/andreskrey/readability.php#known-issues
