### ISSUE TITLE
El encoding está mezclado y se come los acentos

### ISSUE THREAD

**Issue by Zawah** [andreskrey/empleadoEstatalBot#4]
https://www.reddit.com/r/RepublicaArgentina/comments/8bteew/carrefour_se_reconvierte_y_despide_trabajadores/dx9gzz9/

**Comment by andreskrey** [comment]
Si, lo se. El problema viene de Readability. Hace un tiempo le agregue la opcion de normalizar el encoding: https://github.com/andreskrey/readability.php/blob/master/src/Readability.php#L266

Pero aun asi no es suficiente. Hay algunos sitios que el enconding esta tan mezclado que la conversion falla a medio camino o la convierte a algo que a DOMDocument no le gusta. Esoty buscando soluciones :(
